#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /login_check
    
swagger_ui:
    path: /docs
    #methods: GET
    controller: api_platform.swagger.action.ui